services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - chroma
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    restart: unless-stopped

volumes:
  chroma_data: